version: "3.3"
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: development
      DEBUG: node_project_VM2:*
