version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/vagrant/node_project_VM2/nginx-image:/etc/nginx/conf.d
  my-app-1:
    image: voluk/nodejs-image-devops
    ports:
      - "8080:8080"
  my-app-2:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8081:8081"
