version: "3.3"
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - "80:80"
  node-image:
    image: voluk/nodejs-image-devops
    ports:
      - "8080:8080"
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8081:8081"
